Update workflow.yml

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -36,19 +36,18 @@ jobs:
     - name: Add .NET tools to PATH
       run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
 
-    - name: Generate coverage report
-      run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:CoverageReport -reporttypes:Html
+    - name: Generate coverage reports
+      run: |
+        reportgenerator -reports:**/coverage.cobertura.xml -targetdir:CoverageReport -reporttypes:Html;Cobertura
 
-    - name: Upload coverage report
-      uses: actions/upload-artifact@v3
-      with:
-        name: code-coverage-report
-        path: CoverageReport
-        
-    - name: Validate coverage (optional)
+    - name: Validate coverage
       run: |
         COVERAGE_THRESHOLD=80
         COVERAGE=$(grep -Po 'line-rate="\K[0-9]+\.[0-9]+' CoverageReport/Cobertura.xml)
+        if [ -z "$COVERAGE" ]; then
+          echo "Coverage report not found or is empty."
+          exit 1
+        fi
         COVERAGE_INT=${COVERAGE%%.*}
         if [ "$COVERAGE_INT" -lt "$COVERAGE_THRESHOLD" ]; then
           echo "Code coverage ($COVERAGE%) is below the threshold ($COVERAGE_THRESHOLD%)"
@@ -56,3 +55,9 @@ jobs:
         else
           echo "Code coverage ($COVERAGE%) meets the threshold ($COVERAGE_THRESHOLD%)"
         fi
+
+    - name: Upload coverage report
+      uses: actions/upload-artifact@v3
+      with:
+        name: code-coverage-report
+        path: CoverageReport
