Update workflow.yml

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -51,14 +51,20 @@ jobs:
     - name: Install Coveralls.net Tool
       run: dotnet tool install --global coveralls.net
 
+    - name: Find Coverage File
+      id: find_file
+      run: echo "COVERAGE_FILE=$(find $(pwd)/coverage -name coverage.cobertura.xml)" >> $GITHUB_ENV
+
     - name: Debug Information
       run: |
-        pwd
-        ls -al /home/runner/work/easy-chain/easy-chain/coverage/a73bf7c3-29bc-4bae-a26e-ff80165118a7
+        echo "Working Directory: $(pwd)"
+        echo "Listing Coverage Directory:"
+        ls -al $(pwd)/coverage
+        echo "Coverage File: ${{ env.COVERAGE_FILE }}"
 
     - name: Run Coveralls
       env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
       run: |
-        cd /home/runner/work/easy-chain/easy-chain/coverage/a73bf7c3-29bc-4bae-a26e-ff80165118a7
-        csmacnz.Coveralls --reportgenerator -i "coverage.cobertura.xml" --repoToken $COVERALLS_REPO_TOKEN || echo "Coveralls failed"
+        echo "Running Coveralls with coverage file: ${{ env.COVERAGE_FILE }}"
+        csmacnz.Coveralls --reportgenerator -i "${{ env.COVERAGE_FILE }}" --repoToken $COVERALLS_REPO_TOKEN || echo "Coveralls failed"
